# Generated by Django 5.1.1 on 2024-11-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("texttospeech", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttsconverter",
            name="request_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
